---

  - name: Add the Logstash input configuration for file
    template: src=/elastic-stack/templates/file-input.conf dest=/etc/logstash/conf.d/00-file-input.conf

  - name: Add the Logstash filter configuration for apache
    template: src=/elastic-stack/templates/apache-filter.conf dest=/etc/logstash/conf.d/10-apache-filter.conf

  - name: Add the Logstash output configuration to Elasticsearch
    template: src=/elastic-stack/templates/elasticsearch-output.conf dest=/etc/logstash/conf.d/20-elasticsearch-output.conf

  - name: Restart Logstash to apply the configuration change
    service: name=logstash state=restarted

  - unarchive: src=/elastic-stack/logstash-tutorial.log.zip dest=/elastic-stack/input/ remote_src=yes
